/**
 * FactForge — Core Type Definitions
 * Shared state interfaces for the 4-agent LangGraph pipeline
 */

// ─── Claim-level state ───────────────────────────────────────────────────────

export type VerificationStatus =
  | "confirmed"
  | "partially_confirmed"
  | "contradicted"
  | "unverifiable"
  | "pending";

export type Severity = "high" | "medium" | "low" | null;

export interface ClaimHistoryEntry {
  attempt: number;
  claim: string;
  sourceUrl: string;
  verificationStatus: string;
  timestamp: string;
}

export interface ClaimState {
  /** Unique identifier for this claim within the session */
  id: string;
  /** The factual statement extracted by Agent 1 */
  claim: string;
  /** URL of the primary supporting source */
  sourceUrl: string;
  /** The exact text snippet from the source that supports this claim */
  sourceSnippet: string;
  /** Classification result from Agent 2 */
  verificationStatus: VerificationStatus;
  /** Severity of any contradiction/hallucination detected by Agent 3 */
  severity: Severity;
  /** Number of times this claim has been sent back for re-research */
  attemptCount: number;
  /** History of prior attempts for this claim */
  history: ClaimHistoryEntry[];
  /** Confidence score (0–100) computed by Agent 4 */
  confidenceScore: number | null;
  /** Human-readable one-line reason for the confidence score */
  confidenceReason: string | null;
  /** Number of corroborating sources found during verification */
  corroboratingSourcesCount: number;
  /** Trust tier of primary source (0–1) */
  sourceTrustTier: number;
  /** Verification certainty score (0–1) from Agent 2 */
  verificationCertainty: number;
  /** The sub-question this claim answers */
  subQuestion: string;
}

// ─── Pipeline-level state ─────────────────────────────────────────────────────

export type PipelineStage =
  | "idle"
  | "research"
  | "verification"
  | "contradiction_check"
  | "synthesis"
  | "done"
  | "error";

export interface PipelineState {
  /** Session identifier */
  sessionId: string;
  /** User's original topic or claim */
  topic: string;
  /** Sub-questions generated by Agent 1 */
  subQuestions: string[];
  /** All claims being processed */
  claims: ClaimState[];
  /** Current active stage */
  currentStage: PipelineStage;
  /** Final report in Markdown format */
  finalReportMarkdown: string | null;
  /** ISO timestamp when processing started */
  startedAt: string;
  /** ISO timestamp when processing completed */
  completedAt: string | null;
  /** Any error message if the pipeline failed */
  error: string | null;
}

// ─── SSE / Streaming events ───────────────────────────────────────────────────

export type SSEEventType =
  | "stage_change"
  | "agent_log"
  | "claim_update"
  | "loop_triggered"
  | "done"
  | "error";

export interface SSEEvent {
  type: SSEEventType;
  sessionId: string;
  timestamp: string;
  /** Human-readable message for the live log */
  message: string;
  /** Current stage at time of event */
  stage?: PipelineStage;
  /** Claim being acted on (if applicable) */
  claimId?: string;
  /** Index within total claims (for "checking claim 3 of 7" UX) */
  claimIndex?: number;
  /** Total claims count */
  totalClaims?: number;
  /** Updated claim data */
  claim?: Partial<ClaimState>;
  /** Full updated pipeline state */
  pipelineState?: Partial<PipelineState>;
}

// ─── API types ────────────────────────────────────────────────────────────────

export interface VerifyRequest {
  topic: string;
  /** If true, use pre-cached demo data instead of live API calls */
  demo?: boolean;
}

export interface VerifyResponse {
  sessionId: string;
  topic: string;
  createdAt: string;
}

export interface ReportResponse {
  sessionId: string;
  topic: string;
  claims: ClaimState[];
  finalReportMarkdown: string;
  currentStage: PipelineStage;
  completedAt: string | null;
}

// ─── Tavily types ─────────────────────────────────────────────────────────────

export interface TavilySearchResult {
  title: string;
  url: string;
  content: string;
  score: number;
  publishedDate?: string;
}

export interface TavilySearchResponse {
  results: TavilySearchResult[];
  query: string;
}

// ─── Supabase row types ───────────────────────────────────────────────────────

export interface SessionRow {
  id: string;
  topic: string;
  status: "pending" | "running" | "done" | "error";
  pipeline_state: PipelineState | null;
  final_report_markdown: string | null;
  created_at: string;
  updated_at: string;
}
